# Generated by Django 4.2.6 on 2023-11-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='approved',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pseudo_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
