# Generated by Django 4.2.6 on 2023-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_last_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='Shubirei', max_length=150),
            preserve_default=False,
        ),
    ]
