# Generated by Django 4.2.6 on 2023-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='main.author'),
        ),
    ]
