# Generated by Django 4.2.6 on 2023-10-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0002_alter_piece_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
