# Generated by Django 4.2.6 on 2023-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0002_alter_piece_piece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Manwa', 'Manwa'), ('Novel', 'Novel'), ('Comic', 'Comic'), ('Book', 'Book'), ('Magazine', 'Magazine')], max_length=20),
        ),
    ]
