# Generated by Django 4.2.6 on 2023-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0003_alter_piece_piece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Announced', 'Announced'), ('Completed', 'Completed'), ('Deleted', 'Deleted'), ('Dropped', 'Dropped'), ('Editing', 'Editing'), ('Hiatus', 'Hiatus'), ('On-going', 'On-going'), ('One Shot', 'One Shot'), ('Translating', 'Translating')], max_length=20),
        ),
    ]
