# Generated by Django 4.2.6 on 2023-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('piece', '0003_alter_imagecontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='main.author'),
        ),
    ]
