# Generated by Django 4.2.6 on 2023-11-01 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piece', '0004_alter_piece_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceAnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('abandoned', 'Abandoned'), ('in progress', 'In Progress'), ('paused', 'Paused'), ('hoping to start', 'Hoping to Start')], max_length=20)),
                ('summary', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piece.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
