# Generated by Django 4.2.6 on 2023-11-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0004_alter_piece_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='user',
            new_name='users',
        ),
    ]
