# Generated by Django 4.2.6 on 2023-11-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0005_rename_author_piece_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pictures/'),
        ),
    ]
