# Generated by Django 4.2.6 on 2023-11-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_sex_alter_customuser_sex'),
        ('piece', '0005_pieceanotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Manwa', 'Manwa'), ('Novel', 'Novel')], default='Manga', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='author',
            field=models.ManyToManyField(blank=True, to='main.author'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='is_official',
            field=models.CharField(choices=[('Official', 'Official'), ('Anonymous', 'Anonymous')], default='official', max_length=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piece.publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('Announced', 'Announced'), ('Completed', 'Completed'), ('Deleted', 'Deleted'), ('Dropped', 'Dropped'), ('Editing', 'Editing'), ('Hiatus', 'Hiatus'), ('On-going', 'On-going'), ('One Shot', 'One Shot'), ('Translating', 'Translating')], default='Announced', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pieceanotation',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Abandoned', 'Abandoned'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Hoping to Start', 'Hoping to Start')], max_length=20),
        ),
    ]
