# Generated by Django 4.2.6 on 2023-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0006_alter_piece_cover_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piecestatus',
            old_name='ratimg',
            new_name='rating',
        ),
    ]
