# Generated by Django 4.2.6 on 2023-11-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0006_piece_piece_type_alter_piece_author_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pieceanotation',
            constraint=models.UniqueConstraint(fields=('user', 'piece'), name='unique_piece_anotation_for_user'),
        ),
    ]
