# Generated by Django 4.2.6 on 2023-11-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_sex_alter_customuser_sex'),
        ('piece', '0008_piecestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='main.author'),
        ),
    ]
