# Generated by Django 4.2.6 on 2023-12-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0009_alter_piecestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceanotation',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pieceanotation',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piece.piece'),
        ),
    ]
