# Generated by Django 4.2.6 on 2023-11-13 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piece', '0010_alter_piece_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
