# Generated by Django 4.2.6 on 2023-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0010_pieceanotation_page_number_pieceanotation_piece'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pieceanotation',
            name='chapter_or_page_required',
        ),
        migrations.AddConstraint(
            model_name='pieceanotation',
            constraint=models.CheckConstraint(check=models.Q(('chapter__isnull', False), ('page__isnull', False), ('page_number__isnull', False), _connector='OR'), name='chapter_or_page_required'),
        ),
    ]
