# Generated by Django 4.2.6 on 2023-12-06 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piece', '0011_remove_pieceanotation_chapter_or_page_required_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PieceAnotation',
            new_name='PieceAnnotation',
        ),
    ]
