# Generated by Django 4.2.6 on 2023-11-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0011_piece_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='cape_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cape_pictures/'),
        ),
    ]
