# Generated by Django 4.2.6 on 2023-11-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0012_piece_cape_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='cape_picture',
            new_name='cover_picture',
        ),
    ]
